### ISSUE TITLE
groupadd: group 'sfm' already exists

### ISSUE THREAD

**Issue by peterk** [gwu-libraries/sfm-web-harvester#8]
I'm getting multiple errors like this in the log:
_groupadd: group 'sfm' already exists_

...and the container seems to get stuck in restarting mode. Tested on a clean install of SFM 1.5.1.

**Comment by peterk** [comment]
Downgrading to 1.5.0 works.

**Comment by justinlittman** [comment]
Hey @peterk - Are you using internal or external volumes?  (The VOLUME CONFIGURATION section of your .env file.)

**Comment by justinlittman** [comment]
Also, what do you see in the logs for the heritrix container?  Sometimes startup problems with the heritrix container can cause problems for the web harvester container.

If the problem appears to be with the heritrix container, try removing it (`docker-compose rm -vf webharvester heritrix`) and then bringing it back up (`docker-compose up -d`).

I haven't been able to replicate the problem, which is typical for issues I've been having with Heritrix.  I'm going to update the [known issues](http://sfm.readthedocs.io/en/latest/limitations.html) section of the docs.

**Comment by peterk** [comment]
External volumes. Writing to the external volume works fine from other harvesters.

**Comment by peterk** [comment]
Logs for heritrix shows this:
`2017-03-08 10:07:50.968 WARNING thread-57 org.archive.modules.extractor.ExtractorJS.considerString() problem unescaping some javascript
org.apache.commons.lang.exception.NestableRuntimeException: Unable to parse unicode value: tils
	at org.apache.commons.lang.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:337)
	at org.apache.commons.lang.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:287)
	at org.apache.commons.lang.StringEscapeUtils.unescapeJavaScript(StringEscapeUtils.java:406)
	at org.archive.modules.extractor.ExtractorJS.considerString(ExtractorJS.java:170)
	at org.archive.modules.extractor.ExtractorJS.considerStrings(ExtractorJS.java:155)
	at org.archive.modules.extractor.ExtractorJS.considerStrings(ExtractorJS.java:134)
	at org.archive.modules.extractor.ExtractorJS.innerExtract(ExtractorJS.java:121)
	at org.archive.modules.extractor.ContentExtractor.extract(ContentExtractor.java:37)
	at org.archive.modules.extractor.Extractor.innerProcess(Extractor.java:102)
	at org.archive.modules.Processor.innerProcessResult(Processor.java:175)
	at org.archive.modules.Processor.process(Processor.java:142)
	at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
	at org.archive.crawler.framework.ToeThread.run(ToeThread.java:148)
Caused by: java.lang.NumberFormatException: For input string: "tils"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at org.apache.commons.lang.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:331)
	... 12 more`

**Comment by justinlittman** [comment]
And therein lies the problem with Heritrix and the motivation for the [new warning in the docs](http://sfm.readthedocs.io/en/latest/limitations.html) about collecting web resources.

There are no changes in Heritrix between 1.5.1 and 1.5.0.  I suspect the reason it worked in one and not the other is because the Heritrix container was killed and recreated.  When I have web harvesting problems, [this](http://sfm.readthedocs.io/en/latest/troubleshooting.html#web-harvesting-heritrix-problems) is the process I usually follow.

**Comment by justinlittman** [comment]
I'm seeing this after a reboot of SFM server:
```
heritrix_1                | Oracle Corporation OpenJDK Runtime Environment 1.7.0_95-b00
heritrix_1                | Using ad-hoc HTTPS certificate with fingerprint...
heritrix_1                | SHA1:AC:10:4E:0B:50:4D:C2:8A:3F:D9:4A:25:34:D4:76:09:4A:7C:A6:D2
heritrix_1                | Verify in browser before accepting exception.
heritrix_1                | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
heritrix_1                | SLF4J: Defaulting to no-operation (NOP) logger implementation
heritrix_1                | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
heritrix_1                | engine listening at port 8443
heritrix_1                | operator login set per command-line
heritrix_1                | NOTE: We recommend a longer, stronger password, especially if your web 
heritrix_1                | interface will be internet-accessible.
heritrix_1                | Heritrix version: 3.3.0-LBS-2016-02
heritrix_1                | 2017-03-10 11:48:08.677 INFO thread-12 org.archive.crawler.framework.Engine.addJobDirectory() added crawl job: sfm
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
heritrix_1                | groupadd: group 'sfm' already exists
```

**Comment by justinlittman** [comment]
Moving ticket to https://github.com/gwu-libraries/sfm-ui/issues/739. (We use sfm-ui for tickets on all of the SFM repos.)

**Comment by peterk** [comment]
Great, thank you! (one day, when I have a lot of spare time, which is probably never I'd like to write a better web harvester)...
